/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "sage": "#8FA998",
        "sage-light": "#A7BCAD",
        "neutral-soft": "#F7F8F6",
        "inverse-on-surface": "#9c9d99",
        "surface-container-low": "#f3f4ee",
        "outline": "#D1D9D3",
        "on-primary": "#e3feeb",
        "on-surface-variant": "#6A736D",
        "on-primary-fixed": "#2d4437",
        "on-tertiary-fixed-variant": "#5c6442",
        "on-tertiary-fixed": "#404828",
        "surface-container-lowest": "#ffffff",
        "primary-dim": "#405849",
        "tertiary-fixed-dim": "#d8e1b7",
        "error-container": "#fe8983",
        "surface": "#fafaf5",
        "primary": "#4c6455",
        "error": "#9f403d",
        "surface-tint": "#4c6455",
        "secondary-fixed": "#ebdef6",
        "background": "#fafaf5",
        "on-secondary": "#fef6ff",
        "inverse-surface": "#0d0f0c",
        "on-error": "#fff7f6",
        "on-primary-fixed-variant": "#496152",
        "surface-variant": "#dee4da",
        "surface-container": "#ecefe7",
        "inverse-primary": "#d9f5e2",
        "primary-fixed-dim": "#c0dbc9",
        "on-secondary-fixed-variant": "#61586c",
        "surface-dim": "#d5dcd0",
        "primary-fixed": "#cee9d6",
        "tertiary-dim": "#4e5736",
        "on-background": "#2e342d",
        "secondary": "#655b6f",
        "tertiary-container": "#e6f0c4",
        "tertiary": "#5a6341",
        "on-error-container": "#752121",
        "secondary-dim": "#594f63",
        "tertiary-fixed": "#e6f0c4",
        "on-tertiary": "#f4fed1",
        "on-surface": "#2D332F",
        "on-secondary-fixed": "#443c4f",
        "on-primary-container": "#3f5749",
        "surface-container-high": "#e5eae0",
        "error-dim": "#4e0309",
        "on-secondary-container": "#574e62",
        "secondary-container": "#ebdef6",
        "primary-container": "#cee9d6",
        "secondary-fixed-dim": "#ddd0e8",
        "on-tertiary-container": "#525a39",
        "surface-container-highest": "#dee4da",
        "surface-bright": "#fafaf5",
        "outline-variant": "#aeb4aa"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Newsreader", "serif"],
        "label": ["Manrope", "sans-serif"],
        "sans": ["Manrope", "sans-serif"],
        "serif": ["Newsreader", "serif"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
